"""
AI vs Human Text Detector — Flask Web Application

This module serves a pre-trained Linear SVM classifier that predicts whether
a given text input was written by a human or generated by AI.

The model artifacts (clf.pkl and tfidf.pkl) are produced by the training
pipeline in AI-VS-HUMAN.ipynb. See NOTEBOOK_GUIDE.md for details on the
training process.

Usage:
    python main.py          # Starts the server on http://localhost:5000
"""

from flask import Flask, render_template, request
import pickle
import numpy as np

app = Flask(__name__)


@app.route('/', methods=['GET', 'POST'])
def index():
    """
    Handle the main page — display the form and process predictions.

    GET  → Renders the page with an empty result.
    POST → Reads the user's text from the form, runs it through the
           TF-IDF vectorizer and SVM classifier, and displays the prediction.

    Returns:
        Rendered HTML template with the prediction message passed as 'params'.
    """
    # Initialize the message variable at the beginning of the function.
    # This ensures it's always defined, even for a GET request.
    message = " "
    
    if request.method == 'POST':
        # Get the message from the form.
        input_message = request.form['message']
        
        # Load the pre-trained models.
        # It's better practice to load these once outside the function,
        # but for this example, we'll keep it here as per your original code.
        try:
            clf_svm = pickle.load(open('clf.pkl','rb'))
            tfidf = pickle.load(open('tfidf.pkl','rb'))
            
            # Transform the input text using the loaded TF-IDF vectorizer.
            text = tfidf.transform([input_message])
            
            # Predict the result.
            result = clf_svm.predict(text)
            
            # Update the message based on the prediction.
            if(result == 1):
                message = 'The text is likely written by AI'
            else:
                message = "The text is likely written by Human"
        except FileNotFoundError:
            message = "Error: Model files (clf.pkl or tfidf.pkl) not found."

    # The message variable is now guaranteed to have a value.
    return render_template('main.html', params = message)

if __name__ == '__main__':
    import os
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
